person:
    lastName: hello
    age: 18
    boss: false
    birth: 2017/12/12
    maps: {k1: v1,k2: 12}
lists:
  - lisi
  - zhaoliu

xx:
  test:
    hehe: normal
    txtarray: 1,2,3,a  #这种对象形式的，只能单独写一个对象去接收，所以无法使用@value注解获取
    listmap:
      - host: zxj
        port: 10
        active: 9
      - host: ly
        port: 11
        active: 8
    liststr:
      - name
      - value
    map:
      a: a
      b: b